[package]
name = "gocontroll-platform"
version = "0.1.0"
edition = "2021"
target_controller = "IV"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.28"
i2c-linux = "0.1.2"
spidev = "0.5.1"
