[package]
name = "gocontroll-platform"
version = "0.1.0"
edition = "2021"
target_controller = "IV"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
rayon = "1.7.0"
spidev = "0.5.1"
